# numpy学习笔记

numpy：Numeric Python。是一种开源的数值计算扩展。这种工具可用来存储和处理大型矩阵

## 一、Numpy创建

1. arange()：为有序数列。 
   eg： np.arange(1,10,2)其中第一位数字为‘起始数字’，第二位为‘终止数字’（不包括该数字），第三位数字为‘步长’即为间隔数。
   
2. linsapce：生成线段。
    eg：linspace(1,10,5)前两位和上面一样，最后一位为数字个数。
3. reshape(): 为改变shape

In [11]:
import numpy as np

# a = np.array([1,23,4])
# a = np.zeros((3,4))
# a = np.ones((2,3))
# a = np.arange(1,10,2)#创建矩阵
# a = np.linspace(1,10,5)
a = np.arange(1,9,2).reshape((2,2))

print(a)

[[1 3]
 [5 7]]


## 二、numpy属性

在numpy中，数组类为ndarray，其常用的属性如下：
   * ndarray.ndim
   即多维数组的维数。
   * ndarray.shape
   多维数组行、列数
   * ndarray.size
   多维数组的元素个数
   * ndarray.dtype
   多维数组的数据类型（包括int64/32、float64/32，数字越大，精度越高）

In [12]:
import numpy as np

a = np.array([[1,2,3],[2,3,4]])

print(a)

print('number of dim:',a.ndim)
print('shape:',a.shape)
print('size:',a.size)
print('tpye:',a.dtype)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6
tpye: int32


## 三、numpy基础运算

* 一个数的n次方表示为 b = a **n
* 一个数的三角函数为 b = np.tan(a)
* 该数的 '>','<','=='会出现 ‘T/F’ 情况

In [13]:
import numpy as np

a = np.array([10,20,30,40])

# b = a**2
b = np.tan(a)
print(b)
print(a)
print(a>10)

[ 0.64836083  2.23716094 -6.4053312  -1.11721493]
[10 20 30 40]
[False  True  True  True]


### 乘法运算：

1.乘法区别:
   *  a*b 为数的逐个相乘
   * dot(a,b)为矩阵运算

In [14]:
import numpy as np

a = np.arange(4).reshape(2,2)
b = np.array([[0,1],[1,2]])

c = a*b
c_dot = np.dot(a,b) # c_dot2 = a.dot(b)

print(a)
print(b)
print('----------------')
print(c)
print(c_dot)


[[0 1]
 [2 3]]
[[0 1]
 [1 2]]
----------------
[[0 1]
 [2 6]]
[[1 2]
 [3 8]]


2.矩阵的属性:
   * axis = 0是在每一列中进行操作，axis = 1表示在每一行中进行操作。**【修正】axis = i，则numpy沿着第i个下标变化的放下进行操作。** 即当axis=0，即numpy按照第0个下标变化方向进行操作，即沿着列向量进行操作。如果没有指定具体的axis，则定为axis最大数进行操作。
   * argmin/argmax():表示最大/小数的索引
   * median():表示中位数
   * cumsum():表示数累加（当前数以及前面所有数累加和）
   * diff():表示两个数差即为 i-(i-1)的值
   * clip():表示比第一个数小的都为第一个数，比第二个数大的都为第二个数
   * print(a[1,0:2])表示第一行，第0列到第2列（不包含第2列）元素

In [36]:
import numpy as np

a = np.random.random((2,3))
# a=np.random.rand((2,3))
    

print(a)
# print('----------------')
# print('sum:',np.sum(a,axis = 1))
# print('max:',np.max(a,axis = 0))
# print('min:',np.min(a,axis = 1))
# print('----------------')
# print('Minimum index:',np.argmin(a)) #a.argmin() 
# print('Maximum index:',np.argmax(a))
# print('Average:',np.average(a))
# print('Median：',np.median(a))
# print('Cumsum:',np.cumsum(a))
# print('----------------')
# print(np.diff(a))
# print(np.sort(a))
print(np.transpose(a))# print((a.T))
print(np.clip(a,0.1,0.5))
print(a[1,0:2])
print(a.flatten())

[[0.99190695 0.03774663 0.88891632]
 [0.07635337 0.02606829 0.61035743]]
[[0.99190695 0.07635337]
 [0.03774663 0.02606829]
 [0.88891632 0.61035743]]
[[0.5 0.1 0.5]
 [0.1 0.1 0.5]]
[0.07635337 0.02606829]
[0.99190695 0.03774663 0.88891632 0.07635337 0.02606829 0.61035743]


#### array合并

* [:,np.newaxis]是为了给数组增加一个维度
* concatenate（）：是直接通过对axis值的设置来实现横向、竖向合并

In [34]:
import numpy as np

arr1=np.array([1,1,1])
arr2=np.array([2,2,2])

vs=np.vstack((arr1,arr2))   #vertical stack
hs=np.hstack((arr1,arr2))   #horizontal stack
print(vs)
print(hs)
print('----------------')

# arr1_addDimen=arr1[:,np.newaxis]
# arr2_addDimen=arr2[:,np.newaxis]

# vs_d=np.vstack((arr1_addDimen,arr2_addDimen))  
# hs_d=np.hstack((arr1_addDimen,arr2_addDimen))
# print(vs_d)
# print(hs_d)
print('----------------')

ccn=np.concatenate((arr1,arr2),axis=0)####
print(ccn)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
----------------
----------------
[1 1 1 2 2 2]


#### array分割

分割为均等分割：
* 在axis=1时，表示为在水平方向进行分割
* 而vsplit即为vertical split为在垂直方向进行分割

In [42]:
import numpy as np
a=np.arange(12).reshape(3,4)
print(a)

c=np.split(a,3,axis=0) 
# c=np.array_split(a,3,axis=0) #实现不均等分割
print(c)

print(np.vsplit(a,3)) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


#### 赋值（copy&deep copy）

如果用“=”，即表示建立联系的相等，a中数据改变，相等的b中数据也会改变。而 copy（）则只会将数值赋值过去，不会建立联系

In [46]:
import numpy as np
a=np.array([1,2,3,4])
# b=a #copy
b=a.copy() #deep copy
print('a:',a)
print('--------更改数据后输出-------')
a[0]=11

print('a:',a)
print('b:',b)
b is a #判断a、b是相等

a: [1 2 3 4]
--------更改数据后输出-------
a: [11  2  3  4]
b: [1 2 3 4]


False