# Numpy学习笔记


![numpy插图](https://extraimage.net/images/2019/09/23/5ac6e9d90002903efacacdcb8182b8ed.png)

 1. Numpy是什么
 
 2. 引入Numpy的原因是什么
 
 3. ndarry简介
 
 4. 数组的创建
 
 5. 数组的操作
 
 6. 随机模块
 
 7. 统计模块


## 1. Numpy的概念

Numpy是python中开源的用于进行科学计算库，主要包括多维数组与矩阵的运算，具体包含四部分内容：

- 高效的数组对象ndarry
- 支持高效数组运算的操作（可以将数据对象做一个数据进行操作）
- 提供了C/C++,fortran接口，速度更快
- 包含统计，随机数等模块，是其他数据分析开源库的基础

# 2. 引入Numpy的原因

在python中包含了List，为什么要设计与实现numpy呢？原因主要体现在两个方面：

- list中的数据类型各种各样，在python中为了支持类型不固定的数据类型，是在速度和存储做了折中，ndarry要求数组中的每一个元素必须为同一种类型，无论速度和还是存储都比List性能好；
- 引入numpy的目的是为了大规模计算，要求对程序的规模与运行速度能够预测；


# 3. ndarray对象

ndarray是numpy中的高效数组对象，其主要由两部分组成：
 - np.array:实际的数组数据；
 - 元数据：用来描述np.array的数据；
 
 具体的元数据包括：
 
 - axes:轴，用于说明数据是从几个为维度展开，举例来说，一个数值代表一个对象的某一个属性，比如179代表我的身高，而一维数组代表对我各个方面的描述，二维数据代表若干人的描述，三维数据表示从另外一个维度对这些人的描述，比如时间维度，2017年，2018年，2019年关于这些人的描述。
 - rank:秩，表示轴的数目，在线性代数里面学过，代表线性独立的数据轴的数目；
 - ndim:轴的数目
 - shape:数组的形状
 - dtype:数组的数据类型，除了np.arange函数外，其他函数创建的数据类型默认为float类型；
 - size：数组中元素的个数；
 - itemsize：数组中每个元素的大小；


In [28]:
import numpy as np

a=np.arange(1,90)
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

[[1 2]
 [2 4]]
(2, 2)
2
4
int32


# 4. 数组的创建

In [1]:
#到如numpy库

import numpy as np

#基本数组的创建语法
# np.array(list/turple,dtype="datatype")
#如果没有指定类型，默认为int32

ex1=np.array([1,2,3,4,5])
print(ex1)
print(ex1.dtype)

[1 2 3 4 5]
int32


In [34]:
ex2=np.array(1.2,2,3,4,5)
print(ex2)
print(ex2.dtype)

[1.2 2.  3.  4.  5. ]
float64


除了上述方法，numpy还提供了一系列函数帮助我们快速创建数组：

- numpy.arange(start,end,step):类似于python中的range函数，产生的值不包括end；
- numpy.linspace(start,end,num，endpoint=true):在start-end之间产生一个等差数列；
- numpy.logspace(start,end,num):在start-end产生一个等比数组


In [7]:
import numpy as np

ex1=np.arange(1,20,2)
print("arange:")
print(ex1)
print(ex1.dtype)

ex2=np.linspace(1,100,30)
print("linspace include the last point:")
print(ex2)

#创建等差数列
ex3=np.linspace(1,100,30,endpoint=False)
print("linspace not include the last point:")
print(ex3)

#创建等比数列
ex4=np.logspace(1,100,10)
print("logspace")
print(ex4)

arange:
[ 1  3  5  7  9 11 13 15 17 19]
int32
linspace include the last point:
[  1.           4.4137931    7.82758621  11.24137931  14.65517241
  18.06896552  21.48275862  24.89655172  28.31034483  31.72413793
  35.13793103  38.55172414  41.96551724  45.37931034  48.79310345
  52.20689655  55.62068966  59.03448276  62.44827586  65.86206897
  69.27586207  72.68965517  76.10344828  79.51724138  82.93103448
  86.34482759  89.75862069  93.17241379  96.5862069  100.        ]
linspace not include the last point:
[ 1.   4.3  7.6 10.9 14.2 17.5 20.8 24.1 27.4 30.7 34.  37.3 40.6 43.9
 47.2 50.5 53.8 57.1 60.4 63.7 67.  70.3 73.6 76.9 80.2 83.5 86.8 90.1
 93.4 96.7]
logspace
[1.e+001 1.e+012 1.e+023 1.e+034 1.e+045 1.e+056 1.e+067 1.e+078 1.e+089
 1.e+100]


numpy还提供了函数用于创建特殊的数组：

- numpy.ones(shape):创建全1 数组，shape用于表示数组形状的元祖
- numpy.zeros(shape):创建全0数组；
- numpy.full(shape,val):创建值为val的数组；
- numpy.eyes(n):创建维度为n的对角矩阵

In [9]:
import numpy as np

one=np.ones((3,4))
zero=np.zeros((2,5))
arr=np.full((3,2),4)
#创建对角阵
dim=np.eye(3)

print(one)
print(zero)
print(arr)
print(dim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[4 4]
 [4 4]
 [4 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


上述函数还有一种能根据参考数组的形状产生特殊数组的函数：

- np.ones_like(a):根据数组a的形状产生对应的全1数组；
- np.zeros_like(a):根据数组a的形状产生对应的全0数组
- np.full_like(a,val):根据数组a的形状产生值全为Val的数组

In [61]:
import numpy as np

a=np.arange(1,25)
b=a.reshape(2,3,4)
print(b)
# 从这个部分可以看高维数组的表示，最后的坐标的粒度最细，表示数组原子元素的维度，用来表示元素列的维度

one=np.ones_like(b)
zero=np.zeros_like(b)
arr=np.full_like(b,3)

print(one)
print(zero)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]

 [[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]]


## 通过from 函数创建数组

#### 1. numpy.frombuffer 用于实现动态数组。

#### 2. numpy.frombuffer 接受 buffer 输入参数，以流的形式读入转化成 ndarray 对象。

In [13]:
import numpy as np 
#b表示字节流
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  
print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


#### 3.numpy.fromiter 方法从可迭代对象中建立 ndarray 对象，返回一维数组。

In [2]:
import numpy as np 
 
# 使用 range 函数创建列表对象  
list=range(5)
it=iter(list)
 
# 使用迭代器创建 ndarray 
x=np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


#### 4. 从函数中获取数据处理：fromfunction(function,shape,dtype ) 

 ```python
    
    def function(x,y):
        对x,y进行操作，x 表示shape元素的行坐标，y表示列坐标
 
  ```  
    
    `

In [6]:
import numpy as np

def test(x,y):
    return 3*y+x

a=np.fromfunction(test,(3,2),dtype=np.float32)
print(a)

[[0. 3.]
 [1. 4.]
 [2. 5.]]


#### 5. fromstring（string，dtype，count，sep）

In [9]:
import numpy as np

a=np.fromstring("1,2,3,4",dtype=np.int32,sep=",")
print(a)

[1 2 3 4]


# 4. Numpy中数据的运算

   ## 4.1 索引、切片与索引布尔数组
   
   >**索引**用于获取数组中的一个元素；**切片**用于获取数组中子集；
   >索引数组是在数组中指定数组的索引构建一个新数组，布尔数组，是通过将对应的索引的值为TRUE和FALSE选择索引值为True的数组。
   
   ## 4.2 数组中的广播运算
   <br> 
   在numpy中的数组运算时针对数组中的每一个元素的。如果数组中形状不同，numpy会根据数据的维度判断是否可以进行计算，并对数组的维度进行对应的变化，这种机制称为***广播***。
   
   >**广播**是numpy中针对不同维度数组进行计算的方式，可以将数组当做一个变量进行处理；
   > **广播的基本原则**：如果两个数组的后缘维度（trailing dimension，即从末尾开始算起的维度）的轴长度相同，或其中的一方的长度为1，则认为它们是广播兼容的。广播会在缺失和（或）长度为1的维度上进行。（**利用广播进行计算的前提**）
   
   

In [39]:
# 针对一维数组的四种方式

# index
import numpy as np

a=np.linspace(1,10,100,endpoint=True)
print(a)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [8]:
print(a[3])

1.2727272727272727


In [20]:
#2 slice

print(a[4:8:2])

[1.36363636 1.54545455]


In [42]:
print(a[[2,5,8,9]])


[1.18181818 1.45454545 1.72727273 1.81818182]


In [51]:
print(a[a>5])

[ 5.09090909  5.18181818  5.27272727  5.36363636  5.45454545  5.54545455
  5.63636364  5.72727273  5.81818182  5.90909091  6.          6.09090909
  6.18181818  6.27272727  6.36363636  6.45454545  6.54545455  6.63636364
  6.72727273  6.81818182  6.90909091  7.          7.09090909  7.18181818
  7.27272727  7.36363636  7.45454545  7.54545455  7.63636364  7.72727273
  7.81818182  7.90909091  8.          8.09090909  8.18181818  8.27272727
  8.36363636  8.45454545  8.54545455  8.63636364  8.72727273  8.81818182
  8.90909091  9.          9.09090909  9.18181818  9.27272727  9.36363636
  9.45454545  9.54545455  9.63636364  9.72727273  9.81818182  9.90909091
 10.        ]


In [49]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print(arr[[0, 2], [3, 1]])

[ 4 10]


In [52]:
# 针对多维数组

import numpy as np

a=np.random.rand(3,2)
print(a)

[[0.20331011 0.98399475]
 [0.38931678 0.65575899]
 [0.58229647 0.52749253]]


In [53]:
# get the value for row 2 col 1
print(a[1][0])

0.3893167799987016


In [27]:
# get the data for row 2
print(a[1])

[0.38448499 0.85902976]


In [57]:
#get the multiple value from the n dimension array
print(a[[0,1],[0,0]])

[0.20331011 0.38931678]


In [1]:
# 相同维度数组的运算，相同位置的数据进行对应的计算

import numpy as np

a=np.random.rand(3,4)
b=np.random.randint(10,20,(3,4))

print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)


[[0.42028741 0.8516595  0.05605892 0.72219776]
 [0.24657944 0.34267462 0.80547098 0.70231663]
 [0.09464718 0.3934979  0.10107376 0.5001303 ]]
[[19 19 10 11]
 [19 17 18 19]
 [13 13 13 13]]
[[19.42028741 19.8516595  10.05605892 11.72219776]
 [19.24657944 17.34267462 18.80547098 19.70231663]
 [13.09464718 13.3934979  13.10107376 13.5001303 ]]
[[-18.57971259 -18.1483405   -9.94394108 -10.27780224]
 [-18.75342056 -16.65732538 -17.19452902 -18.29768337]
 [-12.90535282 -12.6065021  -12.89892624 -12.4998697 ]]
[[ 7.98546075 16.18153049  0.56058919  7.94417534]
 [ 4.68500943  5.82546848 14.49847762 13.34401604]
 [ 1.23041335  5.11547264  1.31395885  6.50169393]]


In [15]:
# 广播实现的两种方式，第一种方式，末尾维度相同，从高维维度开始拓展
#二维数组实例

import numpy as np

arr1 = np.array([[0, 0, 0],[1, 1, 1],[2, 2, 2], [3, 3, 3]])  #arr1.shape = (4,3)
arr2 = np.array([1, 2, 3])    #arr2.shape = (3,)，将2，变为（4，3）[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]
arr_sum = arr1 + arr2
print(arr_sum)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [13]:
# 广播中的另外一种方式，如果有一维维度为为1，其他维度相同，对维度1的数组进行拓展

import numpy as np

a=np.random.randn(1,4)
b=np.random.randn(3,4)

print(a)
print(b)

print(a+b)

[[ 0.67111046 -1.41533672 -2.09009073 -1.1762139 ]]
[[ 0.26757603 -0.13783438 -0.95699256  0.76363056]
 [ 0.91238975 -0.4221415  -0.0652326  -0.29567624]
 [ 2.30052087 -1.17605494 -1.06132699 -1.20189946]]
[[ 0.9386865  -1.55317111 -3.04708329 -0.41258334]
 [ 1.58350021 -1.83747822 -2.15532333 -1.47189014]
 [ 2.97163134 -2.59139166 -3.15141772 -2.37811336]]


In [3]:
# 高维数组实例

import numpy as np

a=np.random.randn(3,4,2)
b=np.random.randint(10,20,(4,2))

print(a)
print(b)
print(a+b)


[[[-0.94077213 -0.64688278]
  [ 0.91642672 -1.31137695]
  [ 0.43728059  0.86566942]
  [-2.26786714 -1.41037685]]

 [[-0.42424062 -0.09159797]
  [ 0.87892375  0.2159187 ]
  [-0.03286496  1.04231992]
  [ 0.96743734 -0.486036  ]]

 [[ 0.42200189 -2.3140654 ]
  [-1.3561921  -0.56222613]
  [-1.42749434 -3.31607243]
  [-0.897314    0.78257809]]]
[[15 19]
 [17 18]
 [12 14]
 [18 10]]
[[[14.05922787 18.35311722]
  [17.91642672 16.68862305]
  [12.43728059 14.86566942]
  [15.73213286  8.58962315]]

 [[14.57575938 18.90840203]
  [17.87892375 18.2159187 ]
  [11.96713504 15.04231992]
  [18.96743734  9.513964  ]]

 [[15.42200189 16.6859346 ]
  [15.6438079  17.43777387]
  [10.57250566 10.68392757]
  [17.102686   10.78257809]]]


   ## 4.3 数组的拼接操作
   
   ## 4.4 矩阵操作

**索引**用于获取数组中具体的一个元素，如x\[index\](一维数组), x\[index1,index2,...indexn\](n维数组)
同Python中的列表一样支持正负索引

In [20]:
import numpy as np


arr=np.arange(1,20,2)
print(arr[3])
print(arr[-1])

a=np.random.randn(2,3,4)
b=a[0,0,0]
print(a)
print(b)

7
19
[[[ 1.01953518 -1.35332363 -0.30186859 -1.04252611]
  [-1.9910355   0.08246083 -2.1331832  -0.45697969]
  [ 0.76134887 -0.83231473  0.65087906  0.17090254]]

 [[ 1.56251309 -1.00710907 -0.3995578  -2.01981917]
  [ 1.51850561  0.83657977  1.42559744  1.42173064]
  [-0.87950453 -0.99486215 -1.73761466 -0.52022157]]]
1.0195351812681943


**在多维数组中，索引比维度少，则获取一个子数组**

In [4]:
import numpy as np

a=np.random.normal(10,0.5,(3,2))
print(a)

print(a[1])

[[ 9.79676508 10.28457539]
 [ 9.6767669  10.01759738]
 [10.07299692  9.8741995 ]]
[ 9.6767669  10.01759738]


切片用于获得数组的一个子集

In [21]:
import numpy as np

a=np.arange(1,20,2)
print(a)

b=a[1:5]
print(b)
c=a[3:]
print(c)
d=a[:6]
print(d)

[ 1  3  5  7  9 11 13 15 17 19]
[3 5 7 9]
[ 7  9 11 13 15 17 19]
[ 1  3  5  7  9 11]


In [10]:
#对于高维数组也是同样的
import numpy as np 

a=np.random.rand(5,4)
print(a)

b=a[::2,::2]
print(b)

[[0.35351037 0.63593011 0.25701011 0.29006054]
 [0.35280905 0.86882149 0.71299562 0.94354271]
 [0.55272915 0.10602356 0.03780729 0.98643894]
 [0.70512566 0.79338172 0.18844875 0.97708898]
 [0.78516071 0.02090777 0.88321867 0.90712425]]
[[0.35351037 0.25701011]
 [0.55272915 0.03780729]
 [0.78516071 0.88321867]]


In [17]:
# 索引数组

import numpy as np

a=np.arange(2,20,2)
b=a[[2,2,4,3]]
print(b)

#对于高维数组同样如此

c=np.random.poisson(0.6,(8,7))
print(c)
d=c[[0,2,3],[3,4,3]]
print(d)

[ 6  6 10  8]
[[2 0 0 1 1 2 0]
 [0 2 1 2 1 0 1]
 [0 0 0 1 0 0 1]
 [1 0 1 0 1 1 0]
 [0 1 0 0 2 2 0]
 [1 0 1 2 0 0 0]
 [2 0 0 0 0 0 0]
 [0 1 0 1 1 0 0]]
[1 0 0]


# 6. 数据的保存与加载

>在numpy中有三个格式的文件进行数组的存取与加载：
> - txt 或者 csv 文件
> - npy 或者 npz 文件
> - hdf5 文件

- np.savetext与np.loadtext
- np.tofile与np.fromfile
- np.save与np.load

## np.loadtext与np.savetext用户读取.csv文件或.txt文件

In [3]:
import numpy as np

a = np.array(range(20)).reshape((4, 5))
print(a)

# 后缀改为 .txt 一样
filename = 'a.csv'
# 写文件
np.savetxt(filename, a, fmt='%d', delimiter=',')

# 读文件
b = np.loadtxt(filename, dtype=np.int32, delimiter=',')
print(b)

print(b.reshape(b.shape[0],-1))#cannot understand

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


**缺点：**

- 只能保存一维和二维 numpy 数组，当 numpy 数组 a 有多维时，[需要将其 a.reshape((a.shape\[0\], -1)) 后才能用这种方式保存.]
- 不能追加保存，即每次 np.savetxt() 都会覆盖之前的内容。

### np.save与np.load(.npy文件)

**优点：**

- npy 文件可以保存任意维度的 numpy 数组，不限于一维和二维；
- npy 保存了 numpy 数组的结构，保存的时候是什么 shape 和 dtype，取出来时就是什么样的 shape 和 dtype。


**缺点：**

- 只能保存一个 numpy 数组，每次保存会覆盖掉之前文件中存在的内容（如果有的话）。

In [4]:
import numpy as np

a = np.array(range(20)).reshape((2, 2, 5))
print(a)

filename = 'a.npy'
# 写文件
np.save(filename, a)

# 读文件
b = np.load(filename)
print(b)
print(b.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
(2, 2, 5)


## 如果想将多个数据存入到一个文件，这个时候使用.npz压缩文件

- np.savez与np.load

savez函数的第一个参数是文件名，其后的参数都是需要保存的数组，也可以使用关键字参数为数组起一个名字，非关键字参数传递的数组会自动起名为arr_0, arr_1, ...。savez函数输出的是一个压缩文件(扩展名为npz)，其中每个文件都是一个save函数保存的npy文件，文件名对应于数组名。load函数自动识别npz文件，并且返回一个类似于字典的对象，可以通过数组名作为关键字获取数组的内容：

In [5]:
a = np.array([[1,2,3],[4,5,6]])
b = np.arange(0, 1.0, 0.1)
c = np.sin(b)
np.savez("result.npz", a, b, sin_array = c)
r = np.load("result.npz")
print("array a:")
print(r["arr_0"]) # 数组a

print("array b:")
print(r["arr_1"]) # 数组b

print("array c:")
print(r["sin_array"]) # 数组c


array a:
[[1 2 3]
 [4 5 6]]
array b:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
array c:
[0.         0.09983342 0.19866933 0.29552021 0.38941834 0.47942554
 0.56464247 0.64421769 0.71735609 0.78332691]


## 备注：如果你用解压软件打开result.npz文件的话，会发现其中有三个文件：arr_0.npy， arr_1.npy， sin_array.npy，其中分别保存着数组a, b, c的内容。

In [8]:
import numpy as np

np.loadtxt?

## 7. Numpy中的统计模块

- np.amin(), np.amax()

- np.ptp()

- np.percentile()

- np.median()

- np.mean()

- np.average()

- np.std(), np.var()

- np.sum()

In [5]:
# 统计数组中的最大值与最小值
# np.amin()与np.amax()

import numpy as np

a=np.random.randn(3,5)
print(a)

acolmin=np.amin(a,0)
arowmin=np.amin(a,1)
print(acolmin,arommin)
print(np.amin(a))

acolmax=np.amax(a,0)
arowmax=np.amax(a,1)
amax=np.amax(a)
print(acolmax)
print(arowmax)
print(amax)


[[ 0.36402826  0.70381959  2.25050438 -0.30092241  0.30840146]
 [-0.48127056 -1.65429281  0.07762795 -0.17812492  0.16632006]
 [ 0.77056925 -0.16808885 -0.97221617 -0.21449733  1.11756943]]
[-0.48127056 -1.65429281 -0.97221617 -0.30092241  0.16632006] [-2.29366031 -0.84196155 -2.35968708]
-1.6542928126322356
[ 0.77056925  0.70381959  2.25050438 -0.17812492  1.11756943]
[2.25050438 0.16632006 1.11756943]
2.2505043828486992


In [7]:
# 计算数组中元素的偏差

import numpy as np

a=np.random.normal(8,2,(3,4))
print(a)

print(np.ptp(a))

[[ 3.40090347  7.4749965   8.99551016  7.52687275]
 [ 9.03826786  7.42950996 10.16626793  5.39218498]
 [ 9.98843583  8.13021606  9.5870617   6.85360748]]
6.7653644634076855


In [9]:
# 计算数组中的分位数

import numpy as np

a=np.random.randint(10,30,(3,4))
print(a)

#percentile(a,q,aixes),根据轴来取分位数

quar=np.percentile(a,0.15,0)
quarcol=np.percentile(a,0.15,1)
quara=np.percentile(a,0.15)

print(quar)
print(quarcol)
print(quara)

[[29 19 11 19]
 [10 15 16 21]
 [16 17 13 18]]
[10.018 15.006 11.006 18.003]
[11.036  10.0225 13.0135]
10.0165


In [5]:
#mean 计算数组中的平均数，同样实现的包括整个数组，及坐标轴两个维度

import numpy as np

a=np.random.binomial(100,0.5,(3,4))
print(a)

amean=np.mean(a)
cmean=np.mean(a,0)
rmean=np.mean(a,1)
print(amean)
print(cmean)
print(rmean)




[[52 46 51 55]
 [44 54 41 46]
 [47 54 55 49]]
49.5
[47.66666667 51.33333333 49.         50.        ]
[51.   46.25 51.25]


In [8]:
# average(),计算加权平均数，如过没有设定权值，作用和mean函数相同。

import numpy as np 

a=np.array([1,2,3,4])
weights=[4,3,2,1]
amean=np.average(a)
print(amean)
ave=np.average(a,weights=weights)
print(ave)


2.5
2.0


In [11]:
#计算数据的标准差与方差

import numpy as np 

a=np.random.randint(100,200,(3,4))
print(a)

print(np.std(a))
print(np.std(a,0))
print(np.std(a,1))

print(np.var(a))
print(np.var(a,0))
print(np.var(a,1))


[[130 127 195 146]
 [196 182 146 141]
 [189 190 159 171]]
24.807033052924506
[29.60105103 28.00396797 20.72572208 13.12334646]
[27.24426545 23.34925052 12.96871235]
615.3888888888889
[876.22222222 784.22222222 429.55555556 172.22222222]
[742.25   545.1875 168.1875]


In [13]:
#统计元素的和

import numpy as np 

a=np.arange(10,90,20)
print(a)
print(np.sum(a))

[10 30 50 70]
160


## 8. Numpy中的随机数模块

> numpy.random模块提供了大量的随机数模块，是对python中随机数模块的一个补充。

## 8.1 基本的随机数模块

- np.rand():产生指定形状的0-1的随机数组，如果在参数没有指定形状，返回一个0-1的随机数；
- np.randint(low,high,size)：返回指定形状的整数数组
- np.randn()：返回指定形状的满足标准正态分布的随机数组

In [10]:
import numpy as np

#example for np.rand()
a=np.random.rand(2,2)
b=np.random.rand()
print("example for np.rand()")
print(a)
print(b)

example for np.rand()
[[0.90746712 0.09566252]
 [0.52647468 0.80728381]]
0.1801190735101944


In [12]:
import numpy as np

# example for randint
a=np.random.randint(10,100,(3,2))
b=np.random.randint(10,20)
print(a)
print(b)

[[65 70]
 [35 69]
 [51 43]]
10


In [13]:
import numpy as np
# example for randn
a=np.random.randn(3,2)
b=np.random.randn()
print(a)
print(b)

[[-1.22090716  0.03912022]
 [ 0.19627074 -0.02352227]
 [ 0.69597174 -1.07042731]]
0.41194610561549144


## 8.2 与分布相关的函数

- 正态分布：np.normal
- 均匀分布: np.uniform
- 泊松分布: np.poisson
- 二项分布: np.binomial

In [15]:
# 正态分布
import numpy as np

a=np.random.normal(3,0.5,(5,4))
print(a)

[[3.4036182  3.20130289 3.03363136 1.98764307]
 [3.64322258 2.96867478 3.03491612 2.58879942]
 [3.02271349 2.66300012 2.18099623 3.2102186 ]
 [3.55806576 2.82535357 2.54993117 2.8015782 ]
 [3.06369096 2.5186431  2.03847707 3.22091911]]


In [19]:
# 均匀分布
import numpy as np

a=np.random.uniform(10,100,(3,2))
print(a)

[[34.03203933 73.74383428]
 [46.06550913 88.83287068]
 [39.44442484 72.18293373]]


泊松分布，$\lambda$为时间发生的概率

In [21]:
import numpy as np
a=np.random.poisson(0.5,(3,2))
print(a)

[[1 1]
 [0 0]
 [0 0]]


In [23]:
#二项分布
import numpy as np

#np.random.binomial(n,p,size)
a=np.random.binomial(100,0.3,(3,2))
print(a)

[[30 33]
 [24 30]
 [37 24]]


## 8.3 随机选择函数

- np.shuffle(a):随机打乱数组的顺序,不改变原数组
- np.permuation(a)：随机打乱数组顺序，改变原数组
- np.choice(a,[repalce,size,p]):在一维数组a中以概率p选择size的数组，replace表示可以重复使用数组中的元素

In [27]:
import numpy as np

a=np.random.randn(5,4)
print(a)

b=np.random.shuffle(a)
print(a)
print(b)

np.random.permutation(a)
print(a)

c=np.arange(10,20,2)
print(c)
d=np.random.choice(c,size=5)
print(d)


[[-0.88127503 -1.60082693 -1.15999711  0.20979783]
 [-0.05956742 -1.59053033  0.42733685  0.20217797]
 [ 1.39270084 -1.08551503  1.33925895  0.5899807 ]
 [-0.75668636 -0.23104545 -0.5266901  -0.46927937]
 [ 0.82491959 -1.02519687 -0.97925734  0.03891436]]
[[ 1.39270084 -1.08551503  1.33925895  0.5899807 ]
 [-0.75668636 -0.23104545 -0.5266901  -0.46927937]
 [-0.05956742 -1.59053033  0.42733685  0.20217797]
 [ 0.82491959 -1.02519687 -0.97925734  0.03891436]
 [-0.88127503 -1.60082693 -1.15999711  0.20979783]]
None
[[ 1.39270084 -1.08551503  1.33925895  0.5899807 ]
 [-0.75668636 -0.23104545 -0.5266901  -0.46927937]
 [-0.05956742 -1.59053033  0.42733685  0.20217797]
 [ 0.82491959 -1.02519687 -0.97925734  0.03891436]
 [-0.88127503 -1.60082693 -1.15999711  0.20979783]]
[10 12 14 16 18]
[12 16 18 14 16]


In [1]:
import numpy as np

a=np.linspace(10,20,30)

In [2]:
print(a)

[10.         10.34482759 10.68965517 11.03448276 11.37931034 11.72413793
 12.06896552 12.4137931  12.75862069 13.10344828 13.44827586 13.79310345
 14.13793103 14.48275862 14.82758621 15.17241379 15.51724138 15.86206897
 16.20689655 16.55172414 16.89655172 17.24137931 17.5862069  17.93103448
 18.27586207 18.62068966 18.96551724 19.31034483 19.65517241 20.        ]


In [3]:
a[a>14.8]

array([14.82758621, 15.17241379, 15.51724138, 15.86206897, 16.20689655,
       16.55172414, 16.89655172, 17.24137931, 17.5862069 , 17.93103448,
       18.27586207, 18.62068966, 18.96551724, 19.31034483, 19.65517241,
       20.        ])